#!/bin/bash

# Función para mostrar el banner
mostrar_banner() {
    echo -e "\e[1;31m"
    echo      "************************************"
    echo      "*                                  *"
    echo      "*          ~M A X S C A N~         *"
    echo      "*                                  *"
    echo      "************************************"
    echo -e "\e[0m"
}

# Mostrar las opciones al usuario
mostrar_menu() {
    while true; do
        clear
        mostrar_banner
        echo -e "\e[1;35mElige la opción que quieres usar:\e[0m"
        echo -e "\e[1;36m===================================\e[0m" 
        echo "1- Check"
        echo "2- Checkvuln"
        echo -e "\e[1;32m3- Upload \e[0m"
        echo -e "\e[1;31m4- Salir \e[0m"
        read -p "Opción: " opcion

        case $opcion in
            1)
                curl -o check https://raw.githubusercontent.com/Sr-Mxr/check/master/check
                chmod +x check
                ./check
                ;;
            2)
                curl -o checkvuln https://raw.githubusercontent.com/Sr-Mxr/checkvuln/master/checkvuln
                chmod +x checkvuln
                ./checkvuln
                ;;
            3)
                git pull origin main
                ;;
            4)
                break
                ;;
            *)
                echo "Opción no válida. Por favor, seleccione una opción válida."
                ;;
        esac
    done
}

# Ciclo principal del programa
mostrar_menu

